export const stateAndCities = [
  {
    cities: [
      "Nema",
      "Amourj",
      "Timbedra",
      "Oualata",
      "Djiguenni",
      "Bassiknou",
      "Dhar",
    ],
    state: "Houdh Elchargui",
  },
  {
    cities: ["aioun", "koubenni", "Tamchekett", "Tintane"],
    state: "Houdh Elgharbi",
  },
  {
    cities: ["Kiffa", "Kankoussa", "Guerou", "Boumdeid", "Barkewol"],
    state: "Assaba",
  },
  {
    cities: ["Aleg", "Mbagne", "Bababe", "Boghe", "Magtaa lehjar"],
    state: "Brakna",
  },
  {
    cities: ["Kaedi", "M'Bout", "Maghama", "Monguel"],
    state: "Gorgol",
  },
  {
    cities: [
      "Boutilimit",
      "Keur Macene",
      "Mederdra",
      "Ouad Naga",
      "R'Kiz",
      "Rosso",
    ],
    state: "Trarza",
  },
  {
    cities: ["Ghabou", "Ould yenja", "Selibaby"],
    state: "Guidimagha",
  },
  {
    cities: ["Aoujeft", "Chinguity", "Atar", "Ouadan"],
    state: "Adrar",
  },
  {
    cities: ["Akjoujt", "Benichab"],
    state: "Inchiri",
  },
  {
    cities: ["Nouadhibou", "Chami"],
    state: "Daklet nouadhibou",
  },
  {
    cities: ["Zouerat", "Fdeirick", "Bir mogreine"],
    state: "Tiris zemour",
  },
  {
    cities: ["Tidjikja", "Modjeria", "Tichit"],
    state: "Tagant",
  },
  {
    cities: ["Tevragh zeina", "Ksar", "Sebkha"],
    state: "Nouakchott ouest",
  },
  {
    cities: ["El mina", "Arafat", "Raid"],
    state: "Nouakchott sud",
  },
  {
    cities: ["Toujounine", "Dar naim", "Teyaret"],
    state: "Nouakchott Nord",
  },
];

export const cities = [
  "Nouakchott",
  "Nouadhibou",
  "Rosso",
  "Adel Bagrou",
  "Bogué",
  "Kiffa",
  "Zouérat",
  "Kaédi",
  "Boû Gâdoûm",
  "Boutilimit",
  "Atar",
  "Timbédra",
  "Magta Lahjar",
  "Guerou",
  "Sélibaby",
  "Boû Steïlé",
  "Sangrave",
  "Tintane",
  "Néma",
  "Aleg",
  "Tidjikdja",
  "Oualata",
  "Ayoûn el-Atroûs",
  "Bababé",
  "Akjoujt",
  "Chagar",
];
export const specializationsArr = [
  "Dermatologie",
  "Gastro-enterologie",
  "Geriatrie",
  "Hematologie Clinique",
  "Maladies Infectieuses",
  "Medecine Interne",
  "Medecine Preventive",
  "Medecine Legale et du Travail",
  "Nephrologie",
  "Ophtalmologie",
  "Neurologie",
  "Pediatrie",
  "Pneumologie",
  "Psychiatrie",
  "Radiotherapie",
  "Rhumatologie",
];
export let dummyData = [
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Monday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Tuesday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Wednesday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Thursday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Firday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Saturday",
  },
  {
    allDayAvailable: false,
    startTime: null,
    endTime: null,
    breakTime: [[null, null]],
    dayOfWeek: "Sunday",
  },
];
export const formatMoney = (value = 0) => {
  return value?.toFixed(2)?.replace(/\d(?=(\d{3})+\.)/g, "$&,");
};
export const languages = {
  ar: [
    "ar",
    "ar-SA",
    "ar-DZ",
    "ar-EG",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-LB",
    "ar-LY",
    "ar-MA",
    "ar-OM",
    "ar-QA",
    "ar-SA",
    "ar-SD",
    "ar-SY",
    "ar-TN",
    "ar-AE",
    "ar-YE",
  ],
  en: [
    "en-US",
    "en",
    "en-EG",
    "en-AU",
    "en-GB",
    "en-CA",
    "en-NZ",
    "en-IE",
    "en-ZA",
    "en-JM",
    "en-BZ",
    "en-TT",
  ],
  fr: ["fr", "fr-BE", "fr-CA", "fr-CH", "fr-LU"],
};
